// Code generated by mockery v2.51.1. DO NOT EDIT.

package cache

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheInterface is an autogenerated mock type for the CacheInterface type
type MockCacheInterface struct {
	mock.Mock
}

type MockCacheInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheInterface) EXPECT() *MockCacheInterface_Expecter {
	return &MockCacheInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockCacheInterface) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCacheInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheInterface_Expecter) Close(ctx interface{}) *MockCacheInterface_Close_Call {
	return &MockCacheInterface_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockCacheInterface_Close_Call) Run(run func(ctx context.Context)) *MockCacheInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCacheInterface_Close_Call) Return(_a0 error) *MockCacheInterface_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheInterface_Close_Call) RunAndReturn(run func(context.Context) error) *MockCacheInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockCacheInterface) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacheInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheInterface_Expecter) Delete(ctx interface{}, key interface{}) *MockCacheInterface_Delete_Call {
	return &MockCacheInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCacheInterface_Delete_Call) Run(run func(ctx context.Context, key string)) *MockCacheInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheInterface_Delete_Call) Return(_a0 error) *MockCacheInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheInterface_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockCacheInterface) Get(ctx context.Context, key string) (any, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (any, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) any); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheInterface_Expecter) Get(ctx interface{}, key interface{}) *MockCacheInterface_Get_Call {
	return &MockCacheInterface_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheInterface_Get_Call) Run(run func(ctx context.Context, key string)) *MockCacheInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheInterface_Get_Call) Return(_a0 any, _a1 error) *MockCacheInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheInterface_Get_Call) RunAndReturn(run func(context.Context, string) (any, error)) *MockCacheInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeys provides a mock function with given fields: ctx
func (_m *MockCacheInterface) GetKeys(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKeys")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheInterface_GetKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeys'
type MockCacheInterface_GetKeys_Call struct {
	*mock.Call
}

// GetKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheInterface_Expecter) GetKeys(ctx interface{}) *MockCacheInterface_GetKeys_Call {
	return &MockCacheInterface_GetKeys_Call{Call: _e.mock.On("GetKeys", ctx)}
}

func (_c *MockCacheInterface_GetKeys_Call) Run(run func(ctx context.Context)) *MockCacheInterface_GetKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCacheInterface_GetKeys_Call) Return(_a0 []string, _a1 error) *MockCacheInterface_GetKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheInterface_GetKeys_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockCacheInterface_GetKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetLength provides a mock function with no fields
func (_m *MockCacheInterface) GetLength() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLength")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheInterface_GetLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLength'
type MockCacheInterface_GetLength_Call struct {
	*mock.Call
}

// GetLength is a helper method to define mock.On call
func (_e *MockCacheInterface_Expecter) GetLength() *MockCacheInterface_GetLength_Call {
	return &MockCacheInterface_GetLength_Call{Call: _e.mock.On("GetLength")}
}

func (_c *MockCacheInterface_GetLength_Call) Run(run func()) *MockCacheInterface_GetLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCacheInterface_GetLength_Call) Return(_a0 int64, _a1 error) *MockCacheInterface_GetLength_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheInterface_GetLength_Call) RunAndReturn(run func() (int64, error)) *MockCacheInterface_GetLength_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *MockCacheInterface) Set(ctx context.Context, key string, value any) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheInterface_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheInterface_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
func (_e *MockCacheInterface_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *MockCacheInterface_Set_Call {
	return &MockCacheInterface_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *MockCacheInterface_Set_Call) Run(run func(ctx context.Context, key string, value any)) *MockCacheInterface_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockCacheInterface_Set_Call) Return(_a0 error) *MockCacheInterface_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheInterface_Set_Call) RunAndReturn(run func(context.Context, string, any) error) *MockCacheInterface_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheInterface creates a new instance of MockCacheInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheInterface {
	mock := &MockCacheInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
